### ISSUE TITLE
Website Mockups

### ISSUE THREAD

**Issue by shar0391** [MTM6330-F17/FinalProject--Team01#3]

**Comment by lope0154** [comment]
[team1-mockup.pdf](https://github.com/MTM6330-F17/FinalProject--Team01/files/1562939/team1-mockup.pdf)

Here are the mock-ups. They are a bit rough, but they will be polished. It should be enough to let you start the coding.

**Comment by shar0391** [comment]
I think we do not need a big logo in the footer and we should have the navigation links in the footer as well. @shei0080
